pipelines:
  - name: "Northwind Customer Data Cleansing"
    source:
      table: "northwind.bronze.customers"
      
    target:
      table: "northwind.silver.customers"
      
    mode: "scd2"
    join_keys:
      - "customer_id"
      
    transformations:
      - type: "clean_column_names"
      
      - type: "drop_columns"
        columns: 
          - "fax"
          - "contact_title"

      - type: "fill_nulls"
        columns: ["region", "postal_code"]
        value: "N/A"

      - type: "trim_strings"
      
      - type: "clean_phone"
        column: "phone"
        
      - type: "hash_columns"
        columns: ["company_name", "contact_name"]
        target_column: "customer_identity_hash"

  - name: "Northwind Order Enrichment (SQL Join)"
    source:
      table: "northwind.bronze.orders"
      
    target:
      table: "northwind.silver.enriched_orders"
      
    mode: "append"
    
    transformations:
      - type: "clean_column_names"
      
      - type: "cast_datatypes"
        mapping:
          order_date: "timestamp"
          shipped_date: "timestamp"
          freight: "double"

      - type: "extract_date_parts"
        column: "order_date"
      
      - type: "execute_sql"
        query: >
          SELECT 
            o.order_id,
            o.customer_id,
            o.employee_id,
            o.order_date,
            o.freight,
            o.ship_country,
            c.customer_identity_hash,
            c.company_name
          FROM current_df o
          LEFT JOIN northwind.silver.customers c 
            ON o.customer_id = c.customer_id 
            AND c.is_active = True
            
      - type: "add_ingestion_timestamp"
        column_name: "enriched_at"
